### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by MrSkippy** [nl-design-system/lux#237]
## Omschrijving

Belangrijk bericht dat informeert over de huidige activiteit van de gebruiker.

Zie [comment ](https://github.com/nl-design-system/lux/issues/237#issuecomment-2399214115) over Heading styling in Alerts.

- Alerts hebben altijd iconen per type, [zie design](https://www.figma.com/design/515tboh6xpSNziwQu6WyAy/LUX---UI-kit?node-id=225-7569&node-type=frame&t=9HUgs8dO6LZWhBXt-11)
- Een type moet gekozen worden, _mandatory_

## Definition of ready

- [x] Code check op community component gedaan door lux devs
- [x] Styling check op community component gedaan door Aline
- [x] Plan voor missende features of bugs van het community component beschreven in het ticket
- [x] Component tokens zijn beschikbaar
- [x] Ticket doorgenomen met Vlad & Mark

#### Component

- [x] Component is beschikbaar in de index
- [x] Design tokens worden gebruikt

#### Storybook

- [x] Playground story
- [x] States en properties stories
- [x] Korte beschrijving van het component
  - Wat doet het
  - Basis van het component (bijv Utrecht)
  - Aanpassingen en/of uitbreidingen
  - Relatie met andere componenten (bijv. Form field label en Form field)

#### Tests

- [x] Het component rendert
- [x] Aanpassingen en/of uitbreidingen werken (zie ook [Testing components](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-testing--docs))
- [ ] Visual regression test (door LUX)

## Links

- Component: https://www.nldesignsystem.nl/alert
- Figma NLDS: https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=1179-3892
- Community component:
  - CSS: https://nl-design-system.github.io/utrecht/storybook-css/index.html?path=/docs/css-alert--docs
  - React: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-alert--docs
  - Code: https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-react/src/Alert.tsx

**Comment by AlineNap** [comment]
Hoe wordt de heading van de utrecht alert nu gestijlt? Welke tokens hebben jullie devs hiervoor nodig? 
Wat als we proporty toe willen voegen waarbij je kunt kiezen om wel of geen heading toe te voegen? Is dat een feature request?

**Comment by remypar5** [comment]
> Hoe wordt de heading van de utrecht alert nu gestijld? Welke tokens hebben jullie devs hiervoor nodig?

Besproken is het volgende:
We gaan dit in eerste instantie oplossen in de LuxAlert. Dit kan vrij simpel door het volgende toe te passen in de CSS van het component:

```css
.alert {
  --utrecht-heading-1-color: var(--utrecht-alert-color);
  --utrecht-heading-1-font-size: var(--lux-alert-heading-font-size);
  --utrecht-heading-1-line-height: var(--lux-alert-heading-font-size);
}
```

Dit passen we toe op elk kopniveau.

**Comment by MrSkippy** [comment]
@AlineNap 

- Hoe werken iconen?
1. Zoals bij Utrecht: Je moet zelf als developer altijd een icoon toevoegen?
2. Standaard per type: De Alert van type `warning` heeft het icoon met het driehoekje, etc?
3. Type 2 met mogelijkheid van eigen icoon: als je in de property `icon` een icoon meegeeft dan wordt die getoon ipv de standaard.

- Is het mogelijk om geen type mee te geven?

**Comment by AlineNap** [comment]
@MrSkippy type 2. Zoals in de [LUX Figma](https://www.figma.com/design/515tboh6xpSNziwQu6WyAy/LUX---UI-kit?node-id=79-1870) en in ons Webcomponent.

Dat geen type hebben we al meerdere gesprekken over gehad. In Figma niet iig.

**Comment by AlineNap** [comment]
@remypar5  @MrSkippy nog terugkomend op de heading. Is dat niet gewoon heading component erin zetten en dan appearance H-X? Of kun je dat niet als standaard zetten op de alert? In dat geval zijn de alert component tokens voor de heading wel nodig.

**Comment by MrSkippy** [comment]
> [@remypar5](https://github.com/remypar5) [@MrSkippy](https://github.com/MrSkippy) nog terugkomend op de heading. Is dat niet gewoon heading component erin zetten en dan appearance H-X? Of kun je dat niet als standaard zetten op de alert? In dat geval zijn de alert component tokens voor de heading wel nodig.

De developer zet zelf de <Heading> erin, alleen een Heading in een Alert wordt altijd hetzelfde vormgegeven, dus niet de Heading-styling.

**Comment by AlineNap** [comment]
Oke jullie doen iets in de code waardoor elke heading die je in de alert zet de alert.heading tokens krijgt toegepast? 
Heb [een PR](https://github.com/nl-design-system/lux/pull/311) ingeschoten om deze tokens toe te voegen.

**Comment by AlineNap** [comment]
2 vragen voor de devs: 
1. In code van utrecht voor de alert heten de verschillende varianten type. Is het vanuit css/ naming-convention logisch dat geen appearance is zoals bij de button? Is type iets anders?
3. Is het een breaking change/ grote aanpassing als wij de waarde van type qua naamgeving veranderen in loop van de tijd? *Ik heb nu keuze uit 3 verschillende values en weet niet welke beste is.
  - utrecht waard: ok, info, error, warning
  - lux figma waarde: success, info, error, warning
  - NLDS figma waarde: positive, informative, negative, warning

**Comment by MrSkippy** [comment]
1. Er zijn twee gedachtes die je daarop los kan laten:
  1. De waarden `success`, `info`, `error`, `warning` zijn het type alert, zoals `text`, `number` het type van een input aangeven, ook de manier waarop het aan een screenreader wordt doorgegeven kan daar aan gekoppeld zijn, bijv. `aria-live="polite"` bij `info`... 
Een `appearance`-property zal dan meer een styling-optie zijn, bijv. een "outline"-variant van de alert.
  2. De waarden `success`, `info`, `error`, `warning` zijn alleen een styling-optie, dan is `appearance` imho de beste optie.
2. b. is het meest gebruikt.

**Comment by AlineNap** [comment]
@MrSkippy kun je je gedachten checken in de code van Utrecht? Is type nu gekoppeld is aan die aria-live=“polite” etc? Want dan is daar het argument ;)

**Comment by AlineNap** [comment]
Er loopt nog een discussie over de waarde van de types, welke gaan we toepassen? 
Advies uitgevraagd in de [NLDS community ](https://codefornl.slack.com/archives/C01D78C2E4E/p1730112835708489)

> Argument per keuze in volgorde:
> 2.a. Documentatie overnemen van utrecht, meest clean code (import - export zonder wijzigingen)
> 2.b. In de toekomst overgaan naar nl-alert met zo min mogelijk wijzigingen. Het is alleen niet definitief dat dit de nl waardes zijn.
> 2.c. Wat onze gebruikers nu gewend zijn, (mogelijk groeit nl variant hierheen, is dat dan onze input).

**Comment by AlineNap** [comment]
### Design review 6 November

- De heading lijkt geen line-height te hebben of die steekt boven zijn eigen div uit. 
- Icon is 16px zou 24px van de token: utrecht.alert.icon.size moet zijn. 
- Ik kan niet zo goed beoordelen of het icoon goed gepositioneerd wordt. Utrecht gebruikt hier de token `utrecht.alert.icon.inset-block-start` voor. Zie ook de [thread in slack ](https://logius-ux.slack.com/archives/C07FXLM0WH2/p1730884435787419).
- In dark mode moet de paragraph kleur zwart blijven. Pas hiervoor de token `utrecht.alert.color` voor toe. 
- Over de naamgeving van de types ik vind info opzich prima, maar zou adviseren om ok van utrecht over te nemen. Dan is dat onze standaard. Zie hier een gesprek erover die ik heb gevoerd in de [NLDS community](https://codefornl.slack.com/archives/C01D78C2E4E/p1730112835708489).
- De opmerking die over de ok type van Utrecht wordt geplaatst klopt niet, de ok is niet success maar info. Zie screenshot.
- Graag type als titel ipv variant boven de voorbeelden zodat het overeenkomt met de playground en nog de naam erboven dus success, error, warning etc. 
- Vraag: Is het mogelijk om er een inline-link in te plaatsen? Hoop ik :) 


![Image](https://github.com/user-attachments/assets/48062e81-323f-45c7-9c8c-4f24983fd3dd)

![Image](https://github.com/user-attachments/assets/78856448-3f95-4ea0-a4d1-4953b010785d)

![Image](https://github.com/user-attachments/assets/7e77bcf5-76c7-4be1-bea0-6650d2a2a21b)
