### ISSUE TITLE
Form field error message

### ISSUE THREAD

**Issue by MrSkippy** [nl-design-system/lux#240]
## Omschrijving
![Image](https://github.com/user-attachments/assets/87e3fe3e-2ba7-4f7e-aaaa-53cec25ddf49)

## Aanpak
Voorstel Robbert: 

- PR bij Utrecht maken om 'm de features te geven van alert
- nieuwe versie van Utrecht component in gebruik nemen bij RHC
- Ik zou de Utrecht error message wrappen in Lux en de icon instellen op basis van danger/.../...

#### Component

- [ ] Component is beschikbaar in de index
- [ ] Design tokens worden gebruikt

#### Storybook

- [ ] Playground story
- [ ] States en properties stories
- [ ] Korte beschrijving van het component
  - Wat doet het
  - Basis van het component (bijv Utrecht)
  - Aanpassingen en/of uitbreidingen
  - Relatie met andere componenten (bijv. Form field label en Form field)

#### Tests

- [ ] Het component rendert
- [ ] Aanpassingen en/of uitbreidingen werken (zie ook [Testing components](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-testing--docs))
- [ ] Visual regression test (door LUX)

## Repository

LUX

## Links
**LUX**
- [PR met alle form tokens](https://github.com/nl-design-system/lux/pull/200)
- [NLDS Figma](https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=851-939) met lux stijling

NLDS
- [NLDS componenten lijst](https://www.nldesignsystem.nl/form-field-error-message)

**Comment by rwittenberns** [comment]
In NLDS community dev channel discussie openen hoe we onze gewenste features (border radius, background color en icon) kunnen toevoegen, en of dat het beste bij Utrecht of RHC kan.

**Comment by AlineNap** [comment]
### Design review 6 November

**Vragen**
1. Wat doet de property distance precies? Is daar een design token voor oid? 
2. Welke margin krijgt hij dan toebedeeld? 
3. Waarom zit de property distance niet in de playground description en wel bij de error message? Utrecht heeft ze op beide componenten als ik hun Storybook bekijk.
