### ISSUE TITLE
Lead Paragraph

### ISSUE THREAD

**Issue by rwittenberns** [nl-design-system/lux#243]

**Comment by rwittenberns** [comment]
We hebben binnen Logius een Lead Paragraph nodig. Uitzoeken of er binnen NLDS community discussie is gevoerd in welke vorm de lead beschikbaar komt.

**Comment by MrSkippy** [comment]
Slack discussie: https://codefornl.slack.com/archives/C7KDQRXMZ/p1706529616876159
Github discussion: https://github.com/orgs/nl-design-system/discussions/213

**Comment by MrSkippy** [comment]
Wordt een property op LuxParagraph
