### ISSUE TITLE
Form field description

### ISSUE THREAD

**Issue by rwittenberns** [nl-design-system/lux#268]
## Omschrijving

Toont ondersteunende tekst en biedt extra context over de in te vullen informatie.

#### Component

- [ ] Component is beschikbaar in de index
- [ ] Design tokens worden gebruikt

#### Storybook

- [ ] Playground story
- [ ] States en properties stories
- [ ] Korte beschrijving van het component
  - Wat doet het
  - Basis van het component (bijv Utrecht)
  - Aanpassingen en/of uitbreidingen
  - Relatie met andere componenten (bijv. Form field label en Form field)

#### Tests

- [ ] Het component rendert
- [ ] Aanpassingen en/of uitbreidingen werken (zie ook [Testing components](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-testing--docs))
- [ ] Visual regression test (door LUX)

## Links
Component: [Componenten NLDS](https://nldesignsystem.nl/form-field-description)
Figma: [NLDS componenten UI kit](https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=851-924)
Community component: [Storybook Utrecht](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-form-field-description--docs)

**Comment by AlineNap** [comment]
### Design review 6 November

1. De property `appearance` noemt utrecht `status`, waarom deze naamswijziging? 
2. Waarvoor zet utrecht dit in? Lijkt soort error message/ validatie. Iemand hier een idee over?
3. Ik zie momenteel geen use cases. Kunnen we deze property uitschakelen oid?
