### ISSUE TITLE
Radio Group

### ISSUE THREAD

**Issue by AlineNap** [nl-design-system/lux#288]
## Omschrijving

Biedt de mogelijkheid om één optie te selecteren uit een lijst.

### Beoogde Oplossing

Maak een `LuxRadioGroup` component die m.b.v. alleen props een lijst met opties kan weergeven. Iets in de vorm van:

```jsx
<LuxRadioGroup
  name="contact-method"
  label="Voorkeur contactmethode"
  options={[{
    value: 'email',
    label: 'E-mail',
  }, {
    value: 'phone',
    label: 'Telefoon',
  }, {
    value: 'smoke',
    label: 'Rooksignalen',
  }]}
/>
```

Component bestaat uit: 
**Radio-button**
- Issue: https://github.com/nl-design-system/lux/issues/317
- [Figma](https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=948-1789)
- [Storybook](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-radio-button--docs)

**Form-field-radio-option**
- [Figma](https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=1039-2941)
- Storybook: [`RadioButton`](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-radio-button--docs) + [`FormLabel[type="radio"]`](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-form-label--docs), hoe werkt dit in utrecht?

## Definition of ready

- [x] Code check op community component gedaan door lux devs
- [x] Stijling check op community component gedaan door Aline
- [ ] ~~Plan voor missende features of bugs van het community component beschreven in het ticket~~
- [x] Component tokens zijn beschikbaar
- [x] Ticket doorgenomen met Vlad & Mark

#### Component

- [x] Component is beschikbaar in de index
- [x] Design tokens worden gebruikt

#### Storybook

- [x] Playground story
- [x] States en properties stories
- [x] Korte beschrijving van het component
  - Wat doet het
  - Basis van het component (bijv Utrecht)
  - Aanpassingen en/of uitbreidingen
  - Relatie met andere componenten (bijv. Form field label en Form field)

#### Tests

- [x] Het component rendert
- [x] Aanpassingen en/of uitbreidingen werken (zie ook [Testing components](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-testing--docs))
- [ ] Visual regression test (door LUX)

## Links

- Component: https://nldesignsystem.nl/radio-group/
- Figma: https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=954-1910
- Community component:
  - CSS: 
  - React: 
  - Code:

**Comment by AlineNap** [comment]
Besproken tijdens LUX/NLDS op 9 oktober. 
Hiervoor is een PR nodig op Utrecht. Dit doet lux waarschijnlijk. LUX devs zullen ticket aanvullen.

**Comment by AlineNap** [comment]
Stijling check vragen:
- Hoe wordt de radio-button gepositioneerd ten opzicht van het label, gaat dit goed bij verschillende font-sizes? Bij RHC lijkt dat van niet.
- Form-field-radio-option component bestaat niet bij utrecht. Willen wij dat wel?
- Kunnen we token toevoegen voor spacing tussen de form-field-radio-options? Op Utrecht of bij onszelf?
- Hoe wordt het label gestijld van de radiogroep?

**Comment by AlineNap** [comment]
- We maken eigen lux-radio-group.
- @remypar5 vult ticket aan met code eisen.

**Comment by remypar5** [comment]
> * Hoe wordt de radio-button gepositioneerd ten opzicht van het label, gaat dit goed bij verschillende font-sizes? Bij RHC lijkt dat van niet.

De eerste regel van het label is gecentreerd op de Radio button. Tijdens de bouw van dit component gaan we uitzoeken wat de beste manier is.

> * Form-field-radio-option component bestaat niet bij utrecht. Willen wij dat wel? Gaan jullie dit toevoegen aan utrecht code nav ons gesprek van 9 oktober?

We kunnen gebruik maken van `FormLabel[type="radio"]` (zie beschrijving)

> * Kunnen we token toevoegen voor spacing tussen de form-field-radio-options? Op Utrecht of bij onszelf?

Omdat we het component zelf gaan bouwen komt deze spacing token in de `lux` namespace, niet die van `utrecht`.

> * Hoe wordt het label gestijld van de radiogroep?

Met behulp van de `FormLabel` van `utrecht`

**Comment by AlineNap** [comment]
### Design review 6 November

1. Het label graag dikgedrukt, neem de stijling over van de utrecht-form-field-label. Zie screenshot.
2. Graag de mogelijkheid tot een description toevoegen. Zie screenshot 1.
3. Er is geen error message bij invalid, maar dat is wellicht omdat het component nog niet beschikbaar is? Zelfde voor punt 1 & 2 wellicht. 
4. In de playground klik je bij de eerste klik alle radio's uit. Dit zou niet mogelijk moeten zijn.
5. Bij invalid kleurt de checked dot niet mee, hoe komt dat? Wordt de token `utrecht.radio-button.invalid.color` niet toegepast? 
6. Wat doe value in de playground? De tekst die ik in type lijkt niet te verschijnen. 
7. Als ik invalid aanzet worden alle voorbeelden invalid. Als ik die weer uitzet blijft alles invalid gestijlt.
8. Alle voorbeelden zijn soort van aan elkaar gekoppeld? Als ik er 1 check in 1 van de voorbeelden verdwijnt de gecheckte uit een ander voorbeeld. 

 ![Image](https://github.com/user-attachments/assets/86bd4152-6582-4fc3-bd36-cec6fcfde97f)

**Comment by VladAfanasev** [comment]
> ### Design review 6 November
> 1. Het label graag dikgedrukt, neem de stijling over van de `utrecht-form-field-label`. Zie screenshot.  [x]
> 2. Graag de mogelijkheid tot een description toevoegen. Zie screenshot 1.[x]
> 3. Er is geen error message bij invalid, maar dat is wellicht omdat het component nog niet beschikbaar is? Zelfde voor punt 1 & 2 wellicht.[x]
> 4. In de playground klik je bij de eerste klik alle radio's uit. Dit zou niet mogelijk moeten zijn.
> 5. Bij invalid kleurt de checked dot niet mee, hoe komt dat? Wordt de token `utrecht.radio-button.invalid.color` niet toegepast?
---> Token lijkt toegepast te worden, geen idee waarom de checked dot geen kleur krijgt.
> 6. Wat doe value in de playground? De tekst die ik in type lijkt niet te verschijnen. [x]
---> Optie verwijderd uit playground
> 7. Als ik invalid aanzet worden alle voorbeelden invalid. Als ik die weer uitzet blijft alles invalid gestijlt.
> 8. Alle voorbeelden zijn soort van aan elkaar gekoppeld? Als ik er 1 check in 1 van de voorbeelden verdwijnt de gecheckte uit een ander voorbeeld.
> 
> ![Image](https://private-user-images.githubusercontent.com/59806622/383527023-86bd4152-6582-4fc3-bd36-cec6fcfde97f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MTc1MjMsIm5iZiI6MTczMDkxNzIyMywicGF0aCI6Ii81OTgwNjYyMi8zODM1MjcwMjMtODZiZDQxNTItNjU4Mi00ZmMzLWJkMzYtY2VjNmZjZmRlOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE4MjAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTE2OGY2MjgxMDNjMDNmNTNkNTY3N2QzZmI0ODI0ZDBjZmZkNjAyNmZkMmRjNDRlNThmNjJiNmY2MmRmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mp9s76KwavJffUaIP-8jDRY-4oX1o16RjYsitb4oeWI)
