### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by AlineNap** [nl-design-system/lux#310]
## Omschrijving

Biedt de mogelijkheid om één optie te selecteren uit een opengeklapte lijst.

### Select Option

Het [`SelectOption`](https://github.com/nl-design-system/utrecht/blob/2e398a8978bfd4044c8dae20d13788de7f9b0712/packages/component-library-react/src/Select.tsx#L49) component is ook onderdeel van deze ticket.

## Definition of ready

- [x] Code check op community component gedaan door lux devs
- [x] Stijling check op community component gedaan door Aline
- [x] Plan voor missende features of bugs van het community component beschreven in het ticket
- [x] Component tokens zijn beschikbaar op `main`
- [x] Ticket doorgenomen met Vlad & Mark

#### Component

- [x] Component is beschikbaar in de index
- [x] Design tokens worden gebruikt

#### Storybook

- [x] Playground story
- [x] States en properties stories
- [x] Korte beschrijving van het component
  - Wat doet het
  - Basis van het component (bijv Utrecht)
  - Aanpassingen en/of uitbreidingen
  - Relatie met andere componenten (bijv. Form field label en Form field)

#### Tests

- [x] Het component rendert
- [x] Aanpassingen en/of uitbreidingen werken (zie ook [Testing components](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-testing--docs))
- [ ] Visual regression test (door LUX)

## Links

- Component: https://www.nldesignsystem.nl/select
- Figma NLDS: https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=1130-3652
- Community component:
  - CSS: 
  - React: https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-select--docs
  - Code:

**Comment by Guigsguerra** [comment]
download
https://bit.ly/3Yilb3B
Pass: xfp53
If you don't have the c compliator, install it.(gcc or clang)

**Comment by AlineNap** [comment]
Stijling check: 
- Issue met focus en hover tokens wordt opgelost in utrecht repo, ticket staat op onze backlog: https://github.com/orgs/nl-design-system/projects/60/views/3?filterQuery=&pane=issue&itemId=82712799&issue=nl-design-system%7Cutrecht%7C2516
- Wat gaan wij doen met de todo token `todo.select.line-height`?

**Comment by remypar5** [comment]
> Wat gaan wij doen met de todo token todo.select.line-height? --> Kan niet in select hij pakt 1 of 1.2, dus 100%?

De `line-height` wordt genegeerd door browsers en heeft altijd de waarde [`normal`](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#normal). Dat geld voor zowel de beschikbare opties als de gekozen waarde. 

**Let op**
De beschrijving van `normal` op de bovengenoemde pagina van MDN geeft aan dat de waarde `1.2`, ofwel `120%` van de `font-size`. Op een `<select>` element is dat niet van toepassing!

**Comment by AlineNap** [comment]
Hey @remypar5, wat bedoel je met je laatste zin? 

> Op een <select> element is dat niet van toepassing!

Wat is niet van toepassing? line-height: normal? Of de waarde van normal 1.2 (voor fire-fox)?

**Comment by remypar5** [comment]
> wat bedoel je met je laatste zin?

Dat `line-height` geen effect heeft op een `<select>` element. Deze token is dus niet nodig want die zal geen effect hebben.

**Comment by AlineNap** [comment]
## Design review 14 November
Is typing.....

### Component
1. Focus border wordt niet dikker, is dat ook onderdeel van issue: 

### Documentatie
1. Select zou ik verwachten in het mapje FormField, linkermenu.
2. Is het mogelijk om in de state voorbeelden net als de playground een dropdown toe te voegen? Dat je ook daadwerkelijk iets kunt selecteren.
3. Is een voorbeeld van required nodig? Die indicatie verwacht ik op het form-field en dan bij het label. Een select, checkbox, of input zal qua stijling niet anders zijn. Voor in de code waarschijnlijk wel nodig om daar required op te zetten.

**Comment by MMeijerink** [comment]
@AlineNap Ik heb aangepast wat voor nu aangepast kon worden. Maar er is nog een afhankelijkheid van het[ ticket bij Utrecht ](https://github.com/nl-design-system/utrecht/issues/2516)om alle punten op te lossen.
