### ISSUE TITLE
Radio button

### ISSUE THREAD

**Issue by remypar5** [nl-design-system/lux#317]
## Omschrijving

Beschrijft een enkele keuze. Eenmaal gemaakt is de keuze niet te "on-kiezen".

## Links

- Component: https://nldesignsystem.nl/radio-button/
- Figma: https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=948-1789
- Community component:
  - CSS: https://nl-design-system.github.io/utrecht/storybook-css/index.html?path=/docs/css-radio-button--docs
  - React: https://nl-design-system.github.io/utrecht/storybook-react/index.html?path=/docs/react-radio-button--docs
  - Code: https://github.com/nl-design-system/utrecht/blob/main/packages/component-library-react/src/RadioButton.tsx
  

### Definition of ready

- [x] Code check op community component (door LUX)
- [x] Styling check op community component (door LUX)
- [ ] ~~Plan voor missende features of bugs community component beschreven in ticket~~
- [x] Component tokens zijn beschikbaar op `main`
- [x] Ticket doorgenomen met uitvoerder

#### Component

- [x] Component is beschikbaar in de index
- [x] Design tokens worden gebruikt

#### Storybook

- [x] Playground story
- [x] States en properties stories
- [x] Korte beschrijving van het component
  - Wat doet het
  - Wat doen (speciale) features
  - Relatie met andere componenten (bijv. Form field label en Form field)

#### Tests

- [x] Het component rendert
- [x] Aanpassingen en/of uitbreidingen werken (zie ook [Testing components](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/react_react-testing--docs))
- [ ] Visual regression test (door LUX)

**Comment by AlineNap** [comment]
Tokens zitten in pr: https://github.com/nl-design-system/lux/pull/290

**Comment by AlineNap** [comment]
### Design review 6 November 

1. Het rondje als de radio checken is is nogal groot. Die zou 10px moeten zijn van de token `utrecht.radio-button.icon.size`
2. De radio zelf zou 18px moeten zijn van de token: `utrecht.radio-button.size`
3. Wat betekend required op 1 radio-button?
4. Als we de radio button compleet willen maken hebben we ook nog een description toe te voegen, zie screenshot 1 en [het design in Figma. ](https://www.figma.com/design/jzxqJv4PtgHJdmOJwY6lYg/NLDS---Bibliotheek---LUX-tokens?node-id=1039-2941)
5. Als ik hem op disabled zet krijgt het label niet de disabled stijling. 
6. Ik weet niet of het erg is maar als ik met de boolaons aan de gang ga in de playground klopt de stijling niet meer. De omlijning blijft rood nadat hij een keer op invalid is gezet. Zie screenshot 2. 
7. Is default geen onderdeel van States, in de voorbeelden?
8. Kun je de titel focus veranderen in focus-visible?  
9. De voorbeelden van de default state en de checked state zijn met elkaar verbonden. Als je default aanklikt gaat checked uit. Laat het voorbeeld van checked altijd checked. Zie screenshot 3. 
10. Hoe gaan jullie de radio in het midden positioneren? Zodat het ook goed gaat bij een kleiner font (op mobiel is het font 16px ipv 18px), zie ook [het issue hierover op de backlog](https://github.com/nl-design-system/rijkshuisstijl-community/issues/776). ![Image](https://github.com/user-attachments/assets/bb94f95c-b4c5-4d12-aed7-f39d9d98b429)

![Image](https://github.com/user-attachments/assets/cec6bf63-4cf5-4882-979a-0b8fb46dc6e1)

![Image](https://github.com/user-attachments/assets/c217eff7-4f77-4028-88bc-41f1e49bceeb)

**Comment by VladAfanasev** [comment]
@AlineNap Doorgeven aan Utrecht:
Radio button met disabled state wordt niet correct weergegeven, omdat de tokens overschreven worden. Voor nu accepteren wij dit.
